defmodule Pinchflat.Sources.CustomPoster do
  @moduledoc """
  Validates and stores user-owned source poster overrides.

  Custom posters live beside source metadata under a generated filename. The
  database stores only that filename, so callers never need to expose a
  filesystem path to a browser or API client.
  """

  import Bitwise, only: [&&&: 2]

  alias Pinchflat.HTTP.HTTPClient
  alias Pinchflat.Metadata.MetadataFileHelpers
  alias Pinchflat.Repo
  alias Pinchflat.Sources.Source
  alias Pinchflat.Utils.FilesystemUtils

  @max_size 10 * 1024 * 1024
  @allowed_schemes ["http", "https"]
  @request_options [receive_timeout: 10_000, request_timeout: 30_000]
  @filename_pattern ~r/^custom-poster-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$/
  @ffprobe_args [
    "-v",
    "error",
    "-select_streams",
    "v:0",
    "-show_entries",
    "stream=codec_name,width,height",
    "-of",
    "json"
  ]

  @doc """
  Returns the maximum accepted poster size in bytes.
  """
  def max_size, do: @max_size

  @doc """
  Resolves the stored custom poster path for a source.

  Returns a path only for filenames generated by this module.
  """
  def filepath(%Source{} = source) do
    case source.custom_poster_filename do
      filename when is_binary(filename) ->
        if Regex.match?(@filename_pattern, filename) do
          Path.join(MetadataFileHelpers.metadata_directory_for(source), filename)
        end

      _ ->
        nil
    end
  end

  @doc """
  Stores a validated poster from a local multipart upload.

  The upload filename and reported content type are ignored. The decoded
  image content determines the generated extension.

  Returns `{:ok, %Source{}}` or `{:error, reason}`.
  """
  def set_from_upload(%Source{} = source, %Plug.Upload{path: upload_path}) when is_binary(upload_path) do
    with {:ok, %{size: size, type: :regular}} <- File.stat(upload_path),
         :ok <- validate_size(size) do
      store(source, fn temporary_path -> copy_file(upload_path, temporary_path) end)
    else
      {:ok, _} -> {:error, :invalid_upload}
      {:error, :enoent} -> {:error, :invalid_upload}
      {:error, :too_large} -> {:error, :too_large}
      {:error, _reason} -> {:error, :invalid_upload}
    end
  end

  def set_from_upload(_source, _upload), do: {:error, :invalid_upload}

  @doc """
  Fetches and stores a poster from a public HTTP(S) URL.

  Redirects are not followed by the project HTTP client. The URL host is
  resolved and private, loopback, link-local, multicast, and other reserved
  address ranges are rejected before making the request.

  Returns `{:ok, %Source{}}` or `{:error, reason}`.
  """
  def set_from_url(%Source{} = source, url) when is_binary(url) do
    with {:ok, normalized_url, uri} <- validate_url(url),
         :ok <- ensure_safe_host(uri.host),
         {:ok, body} <- http_client().get(normalized_url, [], @request_options),
         :ok <- validate_body(body),
         :ok <- validate_size(byte_size(body)) do
      store(source, fn temporary_path -> File.write(temporary_path, body) end)
    else
      {:error, reason} -> {:error, normalize_remote_error(reason)}
    end
  end

  def set_from_url(_source, _url), do: {:error, :invalid_url}

  @doc """
  Removes the custom poster reference and deletes its owned file, if present.

  Returns `{:ok, %Source{}}` or `{:error, :save_failed}`.
  """
  def remove(%Source{} = source) do
    old_source = source

    case Repo.update(Ecto.Changeset.change(source, custom_poster_filename: nil)) do
      {:ok, updated_source} ->
        delete_owned_file(old_source)
        {:ok, updated_source}

      {:error, _changeset} ->
        {:error, :save_failed}
    end
  end

  @doc false
  def delete_owned_file(%Source{} = source) do
    case filepath(source) do
      nil ->
        :ok

      path ->
        case FilesystemUtils.delete_file_and_remove_empty_directories(path) do
          :ok ->
            :ok

          {:error, :enoent} ->
            :ok

          {:error, reason} ->
            require Logger
            Logger.warning("Could not remove custom poster #{inspect(path)}: #{inspect(reason)}")
            :ok
        end
    end
  end

  defp store(%Source{} = source, writer) do
    metadata_directory = MetadataFileHelpers.metadata_directory_for(source)

    with :ok <- File.mkdir_p(metadata_directory) do
      temporary_path = Path.join(metadata_directory, ".custom-poster-upload-#{Ecto.UUID.generate()}.tmp")

      try do
        case writer.(temporary_path) do
          :ok -> store_validated(source, temporary_path, metadata_directory)
          {:error, reason} -> {:error, reason}
        end
      after
        _ = File.rm(temporary_path)
      end
    end
  end

  defp store_validated(source, temporary_path, metadata_directory) do
    with {:ok, extension} <- validate_image(temporary_path),
         filename = "custom-poster-#{Ecto.UUID.generate()}.#{extension}",
         final_path = Path.join(metadata_directory, filename),
         :ok <- File.rename(temporary_path, final_path) do
      case save_filename(source, filename) do
        {:ok, updated_source} ->
          delete_owned_file(source)
          {:ok, updated_source}

        {:error, :save_failed} ->
          _ = File.rm(final_path)
          {:error, :save_failed}
      end
    end
  end

  defp save_filename(source, filename) do
    case Repo.update(Ecto.Changeset.change(source, custom_poster_filename: filename)) do
      {:ok, updated_source} ->
        {:ok, updated_source}

      {:error, _changeset} ->
        {:error, :save_failed}
    end
  end

  defp copy_file(source, destination) do
    case File.cp(source, destination) do
      :ok -> :ok
      {:error, _reason} -> {:error, :invalid_upload}
    end
  end

  defp validate_size(size) when is_integer(size) and size <= @max_size, do: :ok
  defp validate_size(_size), do: {:error, :too_large}

  defp validate_body(body) when is_binary(body), do: :ok
  defp validate_body(_body), do: {:error, :invalid_response}

  defp validate_url(url) do
    normalized_url = String.trim(url)

    try do
      case URI.parse(normalized_url) do
        %URI{scheme: scheme, host: host, userinfo: nil} = uri
        when scheme in @allowed_schemes and is_binary(host) and host != "" ->
          {:ok, normalized_url, uri}

        _ ->
          {:error, :invalid_url}
      end
    rescue
      ArgumentError -> {:error, :invalid_url}
    end
  end

  defp ensure_safe_host(host) do
    normalized_host = String.downcase(host)

    cond do
      normalized_host in ["localhost", "localhost.localdomain"] ->
        {:error, :unsafe_url}

      String.ends_with?(normalized_host, ".localhost") ->
        {:error, :unsafe_url}

      true ->
        case resolve_host(normalized_host) do
          {:ok, addresses} when addresses != [] ->
            if Enum.any?(addresses, &private_address?/1), do: {:error, :unsafe_url}, else: :ok

          _ ->
            {:error, :unresolvable_host}
        end
    end
  end

  defp resolve_host(host) do
    case Application.get_env(:pinchflat, :source_poster_dns_resolver) do
      resolver when is_function(resolver, 1) ->
        resolver.(host)

      _ ->
        addresses =
          [:inet, :inet6]
          |> Enum.flat_map(fn family ->
            case :inet.getaddrs(String.to_charlist(host), family) do
              {:ok, resolved} -> resolved
              {:error, _reason} -> []
            end
          end)
          |> Enum.uniq()

        if addresses == [], do: {:error, :unresolvable_host}, else: {:ok, addresses}
    end
  end

  defp private_address?({a, b, c, _d}) do
    a in [0, 10, 127] or
      (a == 100 and b in 64..127) or
      (a == 169 and b == 254) or
      (a == 172 and b in 16..31) or
      (a == 192 and b == 0 and c in [0, 2]) or
      (a == 192 and b == 168) or
      (a == 198 and b in [18, 19, 51]) or
      (a == 203 and b == 0 and c == 113) or
      a >= 224
  end

  defp private_address?({a, b, c, d, e, f, g, h}) do
    ipv4_embedded? = {a, b, c, d, e} == {0, 0, 0, 0, 0} and f in [0, 65_535]

    ipv4_address =
      if ipv4_embedded? do
        {div(g, 256), rem(g, 256), div(h, 256), rem(h, 256)}
      end

    (ipv4_embedded? && private_address?(ipv4_address)) or
      (a == 0 and Enum.all?([b, c, d, e, f, g], &(&1 == 0)) and h in [0, 1]) or
      (a &&& 0xFE00) == 0xFC00 or
      (a &&& 0xFFC0) == 0xFE80 or
      (a &&& 0xFF00) == 0xFF00
  end

  defp validate_image(filepath) do
    try do
      case System.cmd("ffprobe", @ffprobe_args ++ [filepath], stderr_to_stdout: true) do
        {output, 0} ->
          with {:ok, %{"streams" => [%{"codec_name" => codec, "width" => width, "height" => height} | _]}} <-
                 Phoenix.json_library().decode(output),
               true <- is_integer(width) and width > 0 and is_integer(height) and height > 0,
               {:ok, extension} <- extension_for_codec(codec) do
            {:ok, extension}
          else
            _ -> {:error, :invalid_image}
          end

        _ ->
          {:error, :invalid_image}
      end
    rescue
      ErlangError -> {:error, :image_validator_unavailable}
      ArgumentError -> {:error, :image_validator_unavailable}
    end
  end

  defp extension_for_codec(codec) when codec in ["mjpeg", "jpeg"], do: {:ok, "jpg"}
  defp extension_for_codec("png"), do: {:ok, "png"}
  defp extension_for_codec("webp"), do: {:ok, "webp"}
  defp extension_for_codec(_codec), do: {:error, :invalid_image}

  defp normalize_remote_error(:invalid_response), do: :invalid_response
  defp normalize_remote_error(:too_large), do: :too_large
  defp normalize_remote_error(:invalid_image), do: :invalid_image
  defp normalize_remote_error(reason), do: reason

  defp http_client do
    Application.get_env(:pinchflat, :http_client, HTTPClient)
  end
end
